<?php
/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'https://www.eventbriteapi.com';

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static $oAuthAccessToken = 'TODO: Replace';

}
