<?php
/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Address {
    /**
     * TODO: Write general description for this method
     * @param string $address_1 public property
     */
    protected $address_1;

    /**
     * TODO: Write general description for this method
     * @param string $address_2 public property
     */
    protected $address_2;

    /**
     * TODO: Write general description for this method
     * @param string $city public property
     */
    protected $city;

    /**
     * TODO: Write general description for this method
     * @param string $region public property
     */
    protected $region;

    /**
     * TODO: Write general description for this method
     * @param string $postal_code public property
     */
    protected $postal_code;

    /**
     * TODO: Write general description for this method
     * @param string $country public property
     */
    protected $country;

    /**
     * TODO: Write general description for this method
     * @param string $country_name public property
     */
    protected $country_name;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 