<?php
/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeResponse extends Pagination {
    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param string $ticket_class_id public property
     */
    protected $ticket_class_id;

    /**
     * TODO: Write general description for this method
     * @param AttendeeProfile $profile public property
     */
    protected $profile;

    /**
     * TODO: Write general description for this method
     * @param AttendeeAddress $addresses public property
     */
    protected $addresses;

    /**
     * TODO: Write general description for this method
     * @param AttendeeAnswers $answers public property
     */
    protected $answers;

    /**
     * TODO: Write general description for this method
     * @param AttendeeBarcodes $barcodes public property
     */
    protected $barcodes;

    /**
     * TODO: Write general description for this method
     * @param AttendeeTeam $team public property
     */
    protected $team;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 