<?php
/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Discount {
    /**
     * TODO: Write general description for this method
     * @param string $code public property
     */
    protected $code;

    /**
     * TODO: Write general description for this method
     * @param string $amount_off public property
     */
    protected $amount_off;

    /**
     * TODO: Write general description for this method
     * @param string $percent_off public property
     */
    protected $percent_off;

    /**
     * TODO: Write general description for this method
     * @param array $ticket_ids public property
     */
    protected $ticket_ids;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $start_date public property
     */
    protected $start_date;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $end_date public property
     */
    protected $end_date;

    /**
     * TODO: Write general description for this method
     * @param int $quantity_available public property
     */
    protected $quantity_available;

    /**
     * TODO: Write general description for this method
     * @param int $quantity_sold public property
     */
    protected $quantity_sold;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 