<?php
/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Events {
    /**
     * TODO: Write general description for this method
     * @param string $event.name.html public property
     */
    protected $event.name.html;

    /**
     * TODO: Write general description for this method
     * @param string $event.organizer_id public property
     */
    protected $event.organizer_id;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $event.start.utc public property
     */
    protected $event.start.utc;

    /**
     * TODO: Write general description for this method
     * @param string $event.start.timezone public property
     */
    protected $event.start.timezone;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $event.end.utc public property
     */
    protected $event.end.utc;

    /**
     * TODO: Write general description for this method
     * @param string $event.end.timezone public property
     */
    protected $event.end.timezone;

    /**
     * TODO: Write general description for this method
     * @param string $event.currency public property
     */
    protected $event.currency;

    /**
     * TODO: Write general description for this method
     * @param string $event.venue_id public property
     */
    protected $event.venue_id;

    /**
     * TODO: Write general description for this method
     * @param string $event.online_event public property
     */
    protected $event.online_event;

    /**
     * TODO: Write general description for this method
     * @param string $event.listed public property
     */
    protected $event.listed;

    /**
     * TODO: Write general description for this method
     * @param string $event.logo.id public property
     */
    protected $event.logo.id;

    /**
     * TODO: Write general description for this method
     * @param string $event.category_id public property
     */
    protected $event.category_id;

    /**
     * TODO: Write general description for this method
     * @param string $event.subcategory_id public property
     */
    protected $event.subcategory_id;

    /**
     * TODO: Write general description for this method
     * @param string $event.format_id public property
     */
    protected $event.format_id;

    /**
     * TODO: Write general description for this method
     * @param string $event.shareable public property
     */
    protected $event.shareable;

    /**
     * TODO: Write general description for this method
     * @param string $event.invite_only public property
     */
    protected $event.invite_only;

    /**
     * TODO: Write general description for this method
     * @param string $event.password public property
     */
    protected $event.password;

    /**
     * TODO: Write general description for this method
     * @param string $event.capacity public property
     */
    protected $event.capacity;

    /**
     * TODO: Write general description for this method
     * @param string $event.show_remaining public property
     */
    protected $event.show_remaining;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 