<?php namespace Eventbrite\Configurations;

use InvalidArgumentException;
use Exception;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Configuration
{
    private static $className = __CLASS__;
    private static $instance;

    //The base Uri for API calls
    private static $baseUri;

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the oAuthAccessToken with an appropriate value
    public static $oAuthAccessToken;

    private function __construct() {}

    public function getInstance()
    {
        return ( self::$instance ?: ( self::$instance = new self::$className ) );
    }

    public static function baseUri($uri = null)
    {
        if ( self::$baseUri && $uri )
            throw new InvalidArgumentException('Base URI already set! Cannot overwrite!');
        if ( ! self::$baseUri && $uri )
            self::$baseUri = $uri;
        if ( ! self::$baseUri && ! $uri )
            throw new Exception('Configuration not set properly. Missing Base URI!');

        return self::$baseUri;
    }

    public static function token($token = null)
    {
        if ( self::$oAuthAccessToken && $token )
            throw new InvalidArgumentException('oAuthAccessToken already set! Cannot overwrite!');
        if ( ! self::$oAuthAccessToken && $token )
            self::$oAuthAccessToken = $token;
        if ( ! self::$oAuthAccessToken && ! $token )
            throw new Exception('Configuration not set properly. Missing oAuthAccessToken!');

        return self::$oAuthAccessToken;
    }
}
