<?php namespace Eventbrite\Exceptions;

use Exception;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */
class APIException extends Exception
{
}
