<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AccessCode extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $code public property
     */
    protected $code;

    /**
     * TODO: Write general description for this method
     * @param array $ticket_ids public property
     */
    protected $ticket_ids;

    /**
     * TODO: Write general description for this method
     * @param DateTime $start_date public property
     */
    protected $start_date;

    /**
     * TODO: Write general description for this method
     * @param DateTime $end_date public property
     */
    protected $end_date;

    /**
     * TODO: Write general description for this method
     * @param int $quantity_available public property
     */
    protected $quantity_available;
}
