<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AddressVenue extends Address
{
    /**
     * TODO: Write general description for this method
     * @param string $latitude public property
     */
    protected $latitude;

    /**
     * TODO: Write general description for this method
     * @param string $longitude public property
     */
    protected $longitude;
}
