<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Address extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $address_1 public property
     */
    protected $address_1;

    /**
     * TODO: Write general description for this method
     * @param string $address_2 public property
     */
    protected $address_2;

    /**
     * TODO: Write general description for this method
     * @param string $city public property
     */
    protected $city;

    /**
     * TODO: Write general description for this method
     * @param string $region public property
     */
    protected $region;

    /**
     * TODO: Write general description for this method
     * @param string $postal_code public property
     */
    protected $postal_code;

    /**
     * TODO: Write general description for this method
     * @param string $country public property
     */
    protected $country;

    /**
     * TODO: Write general description for this method
     * @param string $country_name public property
     */
    protected $country_name;
}
