<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeOrder extends Model
{
    /**
     * TODO: Write general description for this method
     * @param EventOrder $event public property
     */
    protected $event;

    /**
     * TODO: Write general description for this method
     * @param OrderAttendee2 $order public property
     */
    protected $order;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param string $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param Emails $email public property
     */
    protected $email;

    /**
     * TODO: Write general description for this method
     * @param int $quantity public property
     */
    protected $quantity;

    /**
     * TODO: Write general description for this method
     * @param string $status public property
     */
    protected $status;

    /**
     * TODO: Write general description for this method
     * @param string $ticket_id public property
     */
    protected $ticket_id;

    /**
     * TODO: Write general description for this method
     * @param AttendeeProfile $profile public property
     */
    protected $profile;

    /**
     * TODO: Write general description for this method
     * @param AttendeeBarcodes $barcodes public property
     */
    protected $barcodes;

    /**
     * TODO: Write general description for this method
     * @param AttendeeAnswers $answers public property
     */
    protected $answers;

    /**
     * TODO: Write general description for this method
     * @param Costs $costs public property
     */
    protected $costs;
}
