<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeAddress extends Model
{
    /**
     * TODO: Write general description for this method
     * @param Address $home public property
     */
    protected $home;

    /**
     * TODO: Write general description for this method
     * @param Address $ship public property
     */
    protected $ship;

    /**
     * TODO: Write general description for this method
     * @param Address $work public property
     */
    protected $work;
}
