<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeProfile extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $email public property
     */
    protected $email;

    /**
     * TODO: Write general description for this method
     * @param string $first_name public property
     */
    protected $first_name;

    /**
     * TODO: Write general description for this method
     * @param string $last_name public property
     */
    protected $last_name;

    /**
     * TODO: Write general description for this method
     * @param string $prefix public property
     */
    protected $prefix;

    /**
     * TODO: Write general description for this method
     * @param string $suffix public property
     */
    protected $suffix;

    /**
     * TODO: Write general description for this method
     * @param int $age public property
     */
    protected $age;

    /**
     * TODO: Write general description for this method
     * @param string $job_title public property
     */
    protected $job_title;

    /**
     * TODO: Write general description for this method
     * @param string $company public property
     */
    protected $company;

    /**
     * TODO: Write general description for this method
     * @param string $website public property
     */
    protected $website;

    /**
     * TODO: Write general description for this method
     * @param string $blog public property
     */
    protected $blog;

    /**
     * TODO: Write general description for this method
     * @param string $gender public property
     */
    protected $gender;

    /**
     * TODO: Write general description for this method
     * @param DateTime $birth_date public property
     */
    protected $birth_date;

    /**
     * TODO: Write general description for this method
     * @param string $cell_phone public property
     */
    protected $cell_phone;

    /**
     * TODO: Write general description for this method
     * @param string $home_phone public property
     */
    protected $home_phone;

    /**
     * TODO: Write general description for this method
     * @param string $work_phone public property
     */
    protected $work_phone;
}
