<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeTeam extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param DateTime $date_joined public property
     */
    protected $date_joined;

    /**
     * TODO: Write general description for this method
     * @param string $event_id public property
     */
    protected $event_id;
}
