<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeAnswers extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $question_id public property
     */
    protected $question_id;

    /**
     * TODO: Write general description for this method
     * @param string $question public property
     */
    protected $question;

    /**
     * TODO: Write general description for this method
     * @param string $type public property
     */
    protected $type;

    /**
     * TODO: Write general description for this method
     * @param string $answer public property
     */
    protected $answer;
}
