<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class AttendeeResponse extends Pagination
{
    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param string $ticket_class_id public property
     */
    protected $ticket_class_id;

    /**
     * TODO: Write general description for this method
     * @param AttendeeProfile $profile public property
     */
    protected $profile;

    /**
     * TODO: Write general description for this method
     * @param AttendeeAddress $addresses public property
     */
    protected $addresses;

    /**
     * TODO: Write general description for this method
     * @param AttendeeAnswers $answers public property
     */
    protected $answers;

    /**
     * TODO: Write general description for this method
     * @param AttendeeBarcodes $barcodes public property
     */
    protected $barcodes;

    /**
     * TODO: Write general description for this method
     * @param AttendeeTeam $team public property
     */
    protected $team;
}
