<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Contact extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $email public property
     */
    protected $email;

    /**
     * TODO: Write general description for this method
     * @param string $first_name public property
     */
    protected $first_name;

    /**
     * TODO: Write general description for this method
     * @param string $last_name public property
     */
    protected $last_name;
}
