<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Costs extends Model
{
    /**
     * TODO: Write general description for this method
     * @param CurrencyModel $payment_fee public property
     */
    protected $payment_fee;

    /**
     * TODO: Write general description for this method
     * @param CurrencyModel $gross public property
     */
    protected $gross;

    /**
     * TODO: Write general description for this method
     * @param CurrencyModel $eventbrite_fee public property
     */
    protected $eventbrite_fee;

    /**
     * TODO: Write general description for this method
     * @param CurrencyModel $tax public property
     */
    protected $tax;
}
