<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class CurrencyModel extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $currency public property
     */
    protected $currency;

    /**
     * TODO: Write general description for this method
     * @param string $value public property
     */
    protected $value;

    /**
     * TODO: Write general description for this method
     * @param string $display public property
     */
    protected $display;
}
