<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Dates extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param string $created public property
     */
    protected $created;
}
