<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class DateTimeZone extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $timezone public property
     */
    protected $timezone;

    /**
     * TODO: Write general description for this method
     * @param DateTime $local public property
     */
    protected $local;

    /**
     * TODO: Write general description for this method
     * @param DateTime $utc public property
     */
    protected $utc;
}
