<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Destination extends Source
{
    /**
     * TODO: Write general description for this method
     * @param string $s public property
     */
    protected $s;
}
