<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Discount extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $code public property
     */
    protected $code;

    /**
     * TODO: Write general description for this method
     * @param string $amount_off public property
     */
    protected $amount_off;

    /**
     * TODO: Write general description for this method
     * @param string $percent_off public property
     */
    protected $percent_off;

    /**
     * TODO: Write general description for this method
     * @param array $ticket_ids public property
     */
    protected $ticket_ids;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $start_date public property
     */
    protected $start_date;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $end_date public property
     */
    protected $end_date;

    /**
     * TODO: Write general description for this method
     * @param int $quantity_available public property
     */
    protected $quantity_available;

    /**
     * TODO: Write general description for this method
     * @param int $quantity_sold public property
     */
    protected $quantity_sold;
}
