<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Emails extends Model
{
    /**
     * TODO: Write general description for this method
     * @param bool $verified public property
     */
    protected $verified;

    /**
     * TODO: Write general description for this method
     * @param string $email public property
     */
    protected $email;

    /**
     * TODO: Write general description for this method
     * @param bool $primary public property
     */
    protected $primary;
}
