<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class EventSearchResponse extends Pagination
{
    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param Description $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param Description $description public property
     */
    protected $description;

    /**
     * TODO: Write general description for this method
     * @param Logo $logo public property
     */
    protected $logo;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $url public property
     */
    protected $url;

    /**
     * TODO: Write general description for this method
     * @param string $logo_url public property
     */
    protected $logo_url;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $start public property
     */
    protected $start;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $end public property
     */
    protected $end;

    /**
     * TODO: Write general description for this method
     * @param string $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param string $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param int $capacity public property
     */
    protected $capacity;

    /**
     * TODO: Write general description for this method
     * @param string $status public property
     */
    protected $status;

    /**
     * TODO: Write general description for this method
     * @param string $currency public property
     */
    protected $currency;

    /**
     * TODO: Write general description for this method
     * @param string $online_event public property
     */
    protected $online_event;

    /**
     * TODO: Write general description for this method
     * @param string $organizer_id public property
     */
    protected $organizer_id;

    /**
     * TODO: Write general description for this method
     * @param string $venue_id public property
     */
    protected $venue_id;

    /**
     * TODO: Write general description for this method
     * @param string $category_id public property
     */
    protected $category_id;

    /**
     * TODO: Write general description for this method
     * @param string $subcategory_id public property
     */
    protected $subcategory_id;

    /**
     * TODO: Write general description for this method
     * @param string $format_id public property
     */
    protected $format_id;

    /**
     * TODO: Write general description for this method
     * @param OrganizerEventSearch $organizer public property
     */
    protected $organizer;

    /**
     * TODO: Write general description for this method
     * @param VenueSearchResponse $venue public property
     */
    protected $venue;

    /**
     * TODO: Write general description for this method
     * @param Category $category public property
     */
    protected $category;

    /**
     * TODO: Write general description for this method
     * @param Subcategory $subcategory public property
     */
    protected $subcategory;

    /**
     * TODO: Write general description for this method
     * @param Format $format public property
     */
    protected $format;

    /**
     * TODO: Write general description for this method
     * @param array $ticket_classes public property
     */
    protected $ticket_classes;
}
