<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class EventOrder extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param Description $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $url public property
     */
    protected $url;
}
