<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class EventsUserOwned extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param Description $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param Description $description public property
     */
    protected $description;

    /**
     * TODO: Write general description for this method
     * @param OrganizerEventSearch $organizer public property
     */
    protected $organizer;

    /**
     * TODO: Write general description for this method
     * @param VenueSearchResponse $venue public property
     */
    protected $venue;

    /**
     * TODO: Write general description for this method
     * @param array $ticket_classes public property
     */
    protected $ticket_classes;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $url public property
     */
    protected $url;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $start public property
     */
    protected $start;

    /**
     * TODO: Write general description for this method
     * @param DateTimeZone $end public property
     */
    protected $end;

    /**
     * TODO: Write general description for this method
     * @param DateTime $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param DateTime $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param string $timezone public property
     */
    protected $timezone;

    /**
     * TODO: Write general description for this method
     * @param int $capacity public property
     */
    protected $capacity;

    /**
     * TODO: Write general description for this method
     * @param array $categories public property
     */
    protected $categories;

    /**
     * TODO: Write general description for this method
     * @param string $status public property
     */
    protected $status;
}
