<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Fees extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $cost_increase public property
     */
    protected $cost_increase;

    /**
     * TODO: Write general description for this method
     * @param string $gross public property
     */
    protected $gross;

    /**
     * TODO: Write general description for this method
     * @param string $payment_fee public property
     */
    protected $payment_fee;

    /**
     * TODO: Write general description for this method
     * @param string $eventbrite_fee public property
     */
    protected $eventbrite_fee;

    /**
     * TODO: Write general description for this method
     * @param string $transfer_fee public property
     */
    protected $transfer_fee;

    /**
     * TODO: Write general description for this method
     * @param string $tax public property
     */
    protected $tax;

    /**
     * TODO: Write general description for this method
     * @param string $currency public property
     */
    protected $currency;
}
