<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class GetEventDiscountsResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $pagination public property
     */
    protected $pagination;

    /**
     * TODO: Write general description for this method
     * @param array $discounts public property
     */
    protected $discounts;
}
