<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Order extends Model
{
    /**
     * TODO: Write general description for this method
     * @param EventOrder $event public property
     */
    protected $event;

    /**
     * TODO: Write general description for this method
     * @param array $attendees public property
     */
    protected $attendees;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param DateTime $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param DateTime $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param Costs $costs public property
     */
    protected $costs;

    /**
     * TODO: Write general description for this method
     * @param string $first_name public property
     */
    protected $first_name;

    /**
     * TODO: Write general description for this method
     * @param string $last_name public property
     */
    protected $last_name;

    /**
     * TODO: Write general description for this method
     * @param string $email public property
     */
    protected $email;

    /**
     * TODO: Write general description for this method
     * @param string $status public property
     */
    protected $status;

    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;
}
