<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class OrganizerEventSearch extends Model
{
    /**
     * TODO: Write general description for this method
     * @param Description $description public property
     */
    protected $description;

    /**
     * TODO: Write general description for this method
     * @param Logo $logo public property
     */
    protected $logo;

    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $url public property
     */
    protected $url;

    /**
     * TODO: Write general description for this method
     * @param int $num_past_events public property
     */
    protected $num_past_events;

    /**
     * TODO: Write general description for this method
     * @param int $num_future_events public property
     */
    protected $num_future_events;
}
