<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Pagination extends Model
{
    /**
     * TODO: Write general description for this method
     * @param int $object_count public property
     */
    protected $object_count;

    /**
     * TODO: Write general description for this method
     * @param int $page_number public property
     */
    protected $page_number;

    /**
     * TODO: Write general description for this method
     * @param int $page_size public property
     */
    protected $page_size;

    /**
     * TODO: Write general description for this method
     * @param int $page_count public property
     */
    protected $page_count;
}
