<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class RetrieveUserOwnedEventsOrdersResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param array $orders public property
     */
    protected $orders;
}
