<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class RetrieveEventTeamsResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $event public property
     */
    protected $event;

    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param string $attendees_uri public property
     */
    protected $attendees_uri;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $creator public property
     */
    protected $creator;

    /**
     * TODO: Write general description for this method
     * @param string $changed public property
     */
    protected $changed;

    /**
     * TODO: Write general description for this method
     * @param Creator $created public property
     */
    protected $created;

    /**
     * TODO: Write general description for this method
     * @param int $attendee_count public property
     */
    protected $attendee_count;
}
