<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class RetrieveEventTeamAttendeesResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param Pagination $pagination public property
     */
    protected $pagination;

    /**
     * TODO: Write general description for this method
     * @param array $attendees public property
     */
    protected $attendees;
}
