<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class RetrieveYourDetailResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param Emails $emails public property
     */
    protected $emails;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $first_name public property
     */
    protected $first_name;

    /**
     * TODO: Write general description for this method
     * @param string $last_name public property
     */
    protected $last_name;
}
