<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Source extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $event_id public property
     */
    protected $event_id;

    /**
     * TODO: Write general description for this method
     * @param string $order_id public property
     */
    protected $order_id;

    /**
     * TODO: Write general description for this method
     * @param string $attendee_id public property
     */
    protected $attendee_id;

    /**
     * TODO: Write general description for this method
     * @param string $gross public property
     */
    protected $gross;
}
