<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class TicketClasses extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $description public property
     */
    protected $description;

    /**
     * TODO: Write general description for this method
     * @param bool $donation public property
     */
    protected $donation;

    /**
     * TODO: Write general description for this method
     * @param bool $free public property
     */
    protected $free;

    /**
     * TODO: Write general description for this method
     * @param string $minimum_quantity public property
     */
    protected $minimum_quantity;

    /**
     * TODO: Write general description for this method
     * @param string $maximum_quantity public property
     */
    protected $maximum_quantity;

    /**
     * TODO: Write general description for this method
     * @param string $event_id public property
     */
    protected $event_id;

    /**
     * TODO: Write general description for this method
     * @param string $event public property
     */
    protected $event;

    /**
     * TODO: Write general description for this method
     * @param Costs $cost public property
     */
    protected $cost;

    /**
     * TODO: Write general description for this method
     * @param Costs $fee public property
     */
    protected $fee;
}
