<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class TicketClassBody extends Model
{
    /**
     * TODO: Write general description for this method
     * @param string $ticket_class.name public property
     */
    protected $ticket_class = [];
}
