<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class Transfer extends Model
{
    /**
     * TODO: Write general description for this method
     * @param Source $source public property
     */
    protected $source;

    /**
     * TODO: Write general description for this method
     * @param Destination $destination public property
     */
    protected $destination;

    /**
     * TODO: Write general description for this method
     * @param Fees $fees public property
     */
    protected $fees;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param Dates $dates public property
     */
    protected $dates;
}
