<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class UserOwnedEventsOrder extends Model
{
    /**
     * TODO: Write general description for this method
     * @param EventOrder $event public property
     */
    protected $event;

    /**
     * TODO: Write general description for this method
     * @param array $attendees public property
     */
    protected $attendees;
}
