<?php namespace Eventbrite\Models;

/*
 * EventBriteLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/01/2015
 */

class VenueSearchResponse extends Model
{
    /**
     * TODO: Write general description for this method
     * @param AddressVenue $address public property
     */
    protected $address;

    /**
     * TODO: Write general description for this method
     * @param string $resource_uri public property
     */
    protected $resource_uri;

    /**
     * TODO: Write general description for this method
     * @param string $id public property
     */
    protected $id;

    /**
     * TODO: Write general description for this method
     * @param string $name public property
     */
    protected $name;

    /**
     * TODO: Write general description for this method
     * @param string $latitude public property
     */
    protected $latitude;

    /**
     * TODO: Write general description for this method
     * @param string $longitude public property
     */
    protected $longitude;
}
